//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranScope
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntelEntities : DbContext
    {
        public IntelEntities()
            : base("name=IntelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tCategory> tCategories { get; set; }
        public DbSet<tCategoryItem> tCategoryItems { get; set; }
        public DbSet<tContent> tContents { get; set; }
        public DbSet<tContentHistory> tContentHistories { get; set; }
        public DbSet<tContentImport> tContentImports { get; set; }
        public DbSet<tLog> tLogs { get; set; }
        public DbSet<tToken> tTokens { get; set; }
        public DbSet<tUser> tUsers { get; set; }
    }
}
