//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranScope
{
    using System;
    using System.Collections.Generic;
    
    public partial class tContentImport
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string CNTitle { get; set; }
        public string ENTitle { get; set; }
        public string KeySegment { get; set; }
        public string OtherSegment { get; set; }
        public string PurleyContent { get; set; }
        public string Resource { get; set; }
        public string Owner { get; set; }
        public string Audience { get; set; }
        public string Category { get; set; }
        public string Format { get; set; }
        public string Volume { get; set; }
        public string Agency { get; set; }
        public string Stage { get; set; }
        public string Summary { get; set; }
        public string Industry { get; set; }
        public string IndustrialTopic { get; set; }
        public string TechnicalTopic { get; set; }
        public string Workload { get; set; }
        public string Customer { get; set; }
        public string Partner { get; set; }
        public string HWProductTech { get; set; }
        public string SWSolutionOrOtherSupport { get; set; }
        public string KeySentence { get; set; }
        public string IntelHQWebsiteEN { get; set; }
        public string IntelCNWebsite { get; set; }
        public string AWSURLCN { get; set; }
        public string IDLIDCN { get; set; }
        public string Comments { get; set; }
        public string Media { get; set; }
        public string MediaURLs { get; set; }
        public string Abstract { get; set; }
        public string WeChatLink { get; set; }
        public int ContentType { get; set; }
        public string GatedContent { get; set; }
        public string HeadLine { get; set; }
        public string Outline { get; set; }
        public string Link { get; set; }
        public string TextContent { get; set; }
        public string AddUserID { get; set; }
        public string AddUSerName { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string LastEditUserID { get; set; }
        public string LastEditUserName { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public int MoreClassifiers { get; set; }
    }
}
