//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranScope
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLog
    {
        public int ID { get; set; }
        public System.DateTime AddTime { get; set; }
        public int AddUserID { get; set; }
        public string AddUserName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ClientInfo { get; set; }
        public int LogType { get; set; }
    }
}
