//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranScope
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        public tUser()
        {
            this.tTokens = new HashSet<tToken>();
        }
    
        public int ID { get; set; }
        public string LoginName { get; set; }
        public string Roles { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public string PassWord { get; set; }
        public string AddUser { get; set; }
    
        public virtual ICollection<tToken> tTokens { get; set; }
    }
}
